spring:
  config.activate.on-profile: ${SPRING_PROFILES_ACTIVE:local}
  
  redis:
    port: 6379
    clientName: local-demo-redis-client
    #clientType: LETTUCE
    
  devtools:
    restart:
      log-condition-evaluation-delta: true