version: '3'
#https://github.com/bitnami/bitnami-docker-redis
#docker run --name redis -e REDIS_PORT_NUMBER=7000 -p 7000:7000 bitnami/redis:latest
services:
  demo-redis-server:
    container_name: redis-server
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - redis-demo-backend
    #ports:
    #  - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  demo-redis-app:
    container_name: demo-redis-app
    build: ../demo-redis-app
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - redis-demo-backend
    
    #links:
    #  - demo-redis-server
    ports:
      - '8080:8080'
  
networks:
  redis-demo-backend:
    # Use a custom driver
    driver: bridge

volumes:
  redis_data:
    driver: local
                                   