server.port: 9090

spring:   
  #output.ansi.enabled: always
  profiles:    
    active:
    - ${SPRING_PROFILE_ACTIVE:local}

management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true
  endpoint:
    shutdown.enabled: true

logging:
  level:
    root: ${LOG_ROOT_LEVEL:INFO}
    '[org.springframework]': ${LOG_ROOT_LEVEL:WARN}
    '[org.springframework.web]': ${LOG_ROOT_LEVEL:DEBUG}
    '[home.amidja.sb]': ${LOG_APP_LEVEL:DEBUG}